# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: Nvidia.Driver.RTXEnterprise
PackageVersion: "R610 U1"
PackageLocale: en-US
Publisher: NVIDIA Corporation
PackageName: NVIDIA RTX Driver (RTX PRO / Quadro)
PackageUrl: https://www.nvidia.com/en-gb/geforce/drivers/
License: Proprietary (Freeware)
Copyright: © 2011-2026 NVIDIA Corporation
ShortDescription: Drivers for certain lines of non-GeForce NVIDIA graphics cards, primarily the RTX Pro, RTX, and Quadro series of cards used in media studios and in datacenters.
Description: |-
  Drivers for certain lines of non-GeForce NVIDIA graphics cards, primarily the RTX Pro, RTX, and Quadro series of cards used in media studios and in datacenters.

  As of version R610 U1, the driver supports the following lineup models and up： RTX PRO 500, RTX T400, and Quadro T1000.

  As with the regular tool for NVIDIA driver installers, the screens will flicker once when the installation is complete.
Moniker: nvidiadriverrtx
Tags:
- nvidia-display-driver
- nvidiadisplaydriver
- nvidia-graphics-card-driver
- nvidiagraphicscarddriver
- nvidia-hd-audio-driver
- nvidiahdaudiodriver
- nvidia-driver
- nvidiadriver
- workstations
- datacenters
- nvidia-rtx-driver
- nvidiartxdriver
- nvidia-rtx-pro-driver
- nvidiartxprodriver
- nvidia-quadro-driver
- nvidiaquadrodriver
Documentations:
- DocumentLabel: Info on parameters
  DocumentUrl: https://docs.nvidia.com/datacenter/tesla/driver-installation-guide/windows.html
Agreements:
- Agreement: This package is untested, as no test environment was available. Please report any issues here： https://github.com/pl4nty/winget-extras/issues/new?template=package_issue.yml
ManifestType: defaultLocale
ManifestVersion: 1.28.0