# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json

PackageIdentifier: Nvidia.Driver.RTXEnterprise
PackageVersion: "R610 U1"
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.28.0