# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: dyoshikawa.Rulesync
PackageVersion: 27.0.0
InstallerType: portable
Commands:
- rulesync
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dyoshikawa/rulesync/releases/download/v27.0.0/rulesync-windows-x64.exe
  InstallerSha256: 5473F99AF4FCF09C3F9471E05AAFAEF7F4255046BE24D3EEE3CD72B518D69294
ManifestType: installer
ManifestVersion: 1.28.0
