# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Mozilla.Firefox.Portable.RC
PackageVersion: 153.0.3-candidates
ReleaseDate: 2026-08-03
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: firefox\firefox.exe
- RelativeFilePath: firefox\default-browser-agent.exe
- RelativeFilePath: firefox\nmhproxy.exe
- RelativeFilePath: firefox\pingsender.exe
- RelativeFilePath: firefox\plugin-container.exe
- RelativeFilePath: firefox\private_browsing.exe
- RelativeFilePath: firefox\desktop-launcher\desktop-launcher.exe
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/candidates/153.0.3-candidates/build1/win64/en-US/firefox-153.0.3.zip
  InstallerSha256: 625776178E629A0B4345589924A0CA3142BD9EAF19D57AEBFF125C5FA430C20F
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Firefox Release Candidate (Portable x64, en-US)
- Architecture: x86
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/candidates/153.0.3-candidates/build1/win32/en-US/firefox-153.0.3.zip
  InstallerSha256: e6b92369959f137a043608f34b6e75828db7ab5bfe6893e67b9c3a95c0b11c25
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Firefox Release Candidate (Portable x86, en-US)
- Architecture: arm64
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/candidates/153.0.3-candidates/build1/win64-aarch64/en-US/firefox-153.0.3.zip
  InstallerSha256: 7445a8f329bb47a8ceb2a55bb4ff6867a557ec35cd5c7c6a23bd486f9b608274
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Firefox Release Candidate (Portable ARM64, en-US)
ManifestType: installer
ManifestVersion: 1.28.0