# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json

PackageIdentifier: Mozilla.Firefox.Portable.RC
PackageVersion: 153.0.3-candidates
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.28.0