# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.28.0.schema.json

PackageIdentifier: Microsoft.Outlook
PackageVersion: 1.2026.730.100
PackageLocale: cy
PackageName: Outlook ar gyfer Windows
ShortDescription: Mae Outlook for Windows newydd yn brofiad e-bost o'r radd flaenaf sydd am ddim i unrhyw un sydd â Windows. 
Tags:
- outlook-ar-gyfer-windows
- e-bost
- calendrau
- mae-outlook
- ms-outlook
ManifestType: locale
ManifestVersion: 1.28.0
