# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.Outlook
PackageVersion: 1.2026.730.100
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.19041.0
InstallerType: msix
FileExtensions:
- eml
- ics
- msg
- oft
- vcf
PackageFamilyName: Microsoft.OutlookForWindows_8wekyb3d8bbwe
RestrictedCapabilities:
- packageManagement
- runFullTrust
- unvirtualizedResources
ReleaseDate: 2026-07-30
Installers:
- Architecture: x86
  InstallerUrl: https://res.cdn.office.net/nativehost/5mttl/installer/v2/1.2026.730.100/Microsoft.OutlookForWindows_x86.msix
  InstallerSha256: 3D955760B38282E507373962CC611DBD5A905F5E40EF0423D8D45FB39E41203F
  SignatureSha256: F8CB7D9C9A40289473FE147704ADB2CCB1E04A41B8BD6E7473F9BE682BA1CC38
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\WindowsApps\Microsoft.OutlookForWindows_1.2026.730.100_x86__8wekyb3d8bbwe'
- Architecture: x64
  InstallerUrl: https://res.cdn.office.net/nativehost/5mttl/installer/v2/1.2026.730.100/Microsoft.OutlookForWindows_x64.msix
  InstallerSha256: 5BF7AE271645D36452C300D4EAFE5F5C22A955915949857E468F424B003C24F8
  SignatureSha256: 830F5C8DBB44A436754791854C3C59735B6FCD3BEB23D133126EAB095DE5B0F3
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\WindowsApps\Microsoft.OutlookForWindows_1.2026.730.100_x64__8wekyb3d8bbwe'
- Architecture: arm64
  InstallerUrl: https://res.cdn.office.net/nativehost/5mttl/installer/v2/1.2026.730.100/Microsoft.OutlookForWindows_arm64.msix
  InstallerSha256: 338A41DB7E974B6D43E11B667C6D0B99FF4DB0C1248249ACC521126D064F6220
  SignatureSha256: E5CA6DA4B51F23A93E7915141332743527EDCB3F87C079BA88D83BDB681ACC67
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\WindowsApps\Microsoft.OutlookForWindows_1.2026.730.100_arm64__8wekyb3d8bbwe'
ManifestType: installer
ManifestVersion: 1.28.0
