# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.28.0.schema.json

PackageIdentifier: Microsoft.Outlook
PackageVersion: 1.2026.730.100
PackageLocale: el
PackageName: Outlook για Windows
PackageUrl: https://support.microsoft.com/el-gr/outlook/getstarted/getting-started-with-the-new-outlook-for-windows
ShortDescription: Το νέο Outlook για Windows αποτελεί μια κορυφαία εμπειρία ηλεκτρονικού ταχυδρομείου η οποία είναι δωρεάν για οποιονδήποτε διαθέτει Windows.
Tags:
- outlook-για-windows
- λογαριασμούς-ηλεκτρονικού
- ημερολόγιά
- νέο-outlook
- ms-outlook
ManifestType: locale
ManifestVersion: 1.28.0
