# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json

PackageIdentifier: Microsoft.AppInstaller.Preview
PackageVersion: 1.30.90
DefaultLocale: en
ManifestType: version
ManifestVersion: 1.28.0
