# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.AppInstaller.Preview
PackageVersion: 1.30.90
Platform:
- Windows.Universal
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
Commands:
- winget
FileExtensions:
- winget
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCLibs.14
    MinimumVersion: 14.0.33519.0
  - PackageIdentifier: Microsoft.VCLibs.Desktop.14
    MinimumVersion: 14.0.33728.0
  - PackageIdentifier: Microsoft.WindowsAppRuntime.1.8
    MinimumVersion: 1.8.0
# Commented out to hopefully prevent it from overriding stable Microsoft.AppInstaller installations.
# PackageFamilyName: Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
ReleaseDate: 2026-08-06
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/microsoft/winget-cli/releases/download/v1.30.90-preview/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
  InstallerSha256: 0C11A51A83FA5A7EC4F99622E18E34FF5DCC122997EF7B841D738BA5652F8166
  SignatureSha256: BC471EE65EB3EB06CBF5942354F4A5DA41D4A92EEC285B3A9E357D3E7A2C72E5
- Architecture: x86
  InstallerUrl: https://github.com/microsoft/winget-cli/releases/download/v1.30.90-preview/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
  InstallerSha256: 0C11A51A83FA5A7EC4F99622E18E34FF5DCC122997EF7B841D738BA5652F8166
  SignatureSha256: BC471EE65EB3EB06CBF5942354F4A5DA41D4A92EEC285B3A9E357D3E7A2C72E5
- Architecture: arm64
  InstallerUrl: https://github.com/microsoft/winget-cli/releases/download/v1.30.90-preview/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
  InstallerSha256: 0C11A51A83FA5A7EC4F99622E18E34FF5DCC122997EF7B841D738BA5652F8166
  SignatureSha256: BC471EE65EB3EB06CBF5942354F4A5DA41D4A92EEC285B3A9E357D3E7A2C72E5
ManifestType: installer
ManifestVersion: 1.28.0
