# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json
PackageIdentifier: Microsoft.SystemCenter.ServiceManager.Backup
PackageVersion: 10.25.1523
DefaultLocale: en
ManifestType: version
ManifestVersion: 1.28.0