# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json

PackageIdentifier: Microsoft.365CompanionApps
PackageVersion: 2.2605.21000
DefaultLocale: en
ManifestType: version
ManifestVersion: 1.28.0