# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.Portable
PackageVersion: "153"
PackageLocale: en
Publisher: Mozilla
PublisherUrl: https://www.mozilla.org/
PublisherSupportUrl: https://support.mozilla.org/
PrivacyUrl: https://www.mozilla.org/privacy/firefox/
Author: Mozilla Foundation
PackageName: Mozilla Firefox (Portable)
PackageUrl: https://www.mozilla.org/firefox/
License: MPL-2.0
LicenseUrl: https://www.mozilla.org/MPL/2.0
Copyright: © Firefox and Mozilla Developers; available under the MPL 2 license.
CopyrightUrl: https://www.mozilla.org/foundation/trademarks/policy
ShortDescription: The portable version of the web browser Firefox. The portable version has its files taken 1:1 from the stable MSIX version, making it as official and stable-versioned as can be.
Moniker: firefoxportable
Tags:
- web-browser
- webbrowser
- gecko
- pdfreader
- quantum
- spidermonkey
- webpages
- websites
- mozilla-firefox-portable
- mozillafirefoxportable
- portable-firefox
- portablefirefox
ReleaseNotesUrl: https://www.firefox.com/en-US/firefox/153.0/releasenotes/
ManifestType: defaultLocale
ManifestVersion: 1.12.0
