# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Microsoft.WindowsAdvancedSettings
PackageVersion: 0.2101.858
PackageLocale: fr
PackageName: Paramètres avancés de Windows
Tags:
- paramètres-avancés-de-windows
- paramètresavancésdewindows
- parametres-avances-de-windows
- parametresavancesdewindows
- repositoires-de-git
- repos-de-git
- file-explorer
- fileexplorer
- 9n8mhtphngvv
ManifestType: locale
ManifestVersion: 1.12.0