# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Microsoft.WindowsAdvancedSettings
PackageVersion: 0.2101.858
PackageLocale: ja
PackageName: Windows 高度な設定
Tags:
- windows高度な設定
- うぃんどうずこうどなせってい
- ウィンドウズコウドナセッテイ
- git-repositories
- git-repos
- file-explorer
- fileexplorer
- 9n8mhtphngvv
ManifestType: locale
ManifestVersion: 1.12.0